# 프로젝트 환경 설정
spring:
  profiles:
    active: prod  # 기본 프로파일 설정: H2, MySQL 실행 시 prod 프로파일로 변경
  data:
    redis:
      host: localhost
      port: 6379
  task:
    scheduling:
      pool:
        size: 10

# H2 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# 테스트 프로파일 설정 (임베디드 Redis 및 H2 데이터베이스)
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

# MySQL 프로파일 설정
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://192.168.219.101:3306/zbdividend?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 6188
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha # 연산자를 알파벳순으로 정렬
    tags-sorter: alpha       # 태그를 알파벳순으로 정렬
    display-request-duration: true # 요청 소요 시간을 표시
  api-docs:
    path: /v3/api-docs        # 기본 OpenAPI 명세 경로
  packages-to-scan: com.example.demo.controller
